#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin_prestashop=$YNH_APP_ARG_ADMIN
language=$YNH_APP_ARG_LANGUAGE
is_public=$YNH_APP_ARG_IS_PUBLIC
pass=$YNH_APP_ARG_PASSWD
admin_email=$YNH_APP_ARG_ADMIN_EMAIL
email=$admin_email

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path $path)

# Register (book) web path
ynh_webpath_register $app $domain $path_url
[[ ${#pass} -gt 5 ]] || ynh_die \
"The password is too weak, it must be longer than 5 characters"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path
ynh_app_setting_set $app admin $admin_prestashop
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app language $language
ynh_app_setting_set $app pass $pass
ynh_app_setting_set $app email $email

#=================================================
# Check password strength
#=================================================

[[ ${#pass} -gt 5 ]] || ynh_die \
"The password is too weak, it must be longer than 5 characters"

#=================================================
# CREATE A MYSQL DATABASE
#=================================================

db_name=$(ynh_sanitize_dbid $app)
ynh_app_setting_set $app db_name $db_name
ynh_mysql_setup_db $db_name $db_name

#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

# ynh_script_progression --message="Configuring PHP-FPM..." --weight=2

# # Create a dedicated PHP-FPM config
# ynh_add_fpm_config --usage=low --footprint=low
# phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_app_setting_set $app final_path $final_path
mkdir -p $final_path
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source "$final_path"
unzip -quo $final_path/prestashop.zip -d /var/www/prestashop

#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create $app

#=================================================
# Installation de Prestashop
#=================================================

#fix for db_name
sed -i "s/VARCHAR(64)/VARCHAR(512)/" $final_path/install/upgrade/sql/1.6.0.3.sql
sed -i "s/\x27name\x27 => array(\x27type\x27 => self::TYPE_STRING, \x27lang\x27 => true, \x27required\x27 => true, \x27validate\x27 => \x27isTabName\x27, \x27size\x27 => 64),/\x27name\x27 => array(\x27type\x27 => self::TYPE_STRING, \x27lang\x27 => true, \x27required\x27 => true, \x27validate\x27 => \x27isTabName\x27, \x27size\x27 => 512),/" $final_path/classes/Tab.php

pushd $final_path/install/
php7.0 index_cli.php \
		--db_server=localhost \
		--db_user=$db_name \
		--db_password=$db_pwd \
		--db_name=$app \
		--db_driver=amysqli \
		--db_port=3306 \
		--language=${language:0:2} \
		--lastname=$admin_prestashop \
		--firstname=$admin_prestashop \
		--password=$pass \
		--email=$admin_email \
		--domain=$domain \
		--base_uri=$path \
		--prefix=_ps_
popd

sudo rm -fr $final_path/install

#=================================================
# check les permissions
#=================================================

sudo chown -R $app:$app $final_path

#=================================================
# active ssl
#=================================================

mysql -u $db_name -p$db_pwd $app -e "UPDATE ps_configuration SET value=1 WHERE name='PS_SSL_ENABLED';"
mysql -u $db_name -p$db_pwd $app -e "INSERT INTO ps_configuration (id_configuration, id_shop_group, id_shop, name, value, date_add, date_upd) VALUES (NULL, NULL, NULL, 'PS_SSL_ENABLED_EVERYWHERE', '1', NOW(), NOW());"

#=================================================
# Set /etc/hosts
#=================================================

echo -e "127.0.0.1 $domain #PRESTASHOP" | sudo tee -a /etc/hosts

#=================================================
# SETUP SSOWAT
#=================================================

# Make app public if necessary
if [ $is_public -eq 1 ]
then
	# unprotected_uris allows SSO credentials to be passed anyway.
	ynh_app_setting_set $app unprotected_uris "/"
fi

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx

#=================================================
# Nettoyer hosts
#=================================================

sudo sed -i '/#PRESTASHOP/d' /etc/hosts
